spring:
  config:
    import: optional:classpath:.env

  devtools:
    restart:
      enabled: true
    additional-exclude: /src/main/resources/**

  application:
    name: authServer

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          show_sql: true
          format_sql: true

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework:
        security: DEBUG
    org.springframework.security.oauth2: DEBUG